### ISSUE TITLE
[QUESTION] Do not read emission data when emission is turned off

### ISSUE THREAD

**Issue by JiaweiZhuang** [geoschem/gchp_legacy#18]
I remember that in early days, ExtData would skip emission data files if emission is set to `F`. But now it seems that emission data are always being read:
- [run_2days_18core.log](https://github.com/geoschem/gchp/files/2761279/run_2days_18core.log)
- [run_2days_18core_noEMIS.log](https://github.com/geoschem/gchp/files/2761278/run_2days_18core_noEMIS.log)

Two runs take the same time. For short simulations (1~2 days) ExtData takes nearly half of time. Is there a way to skip emission files without messing around `ExtData.rc`? (I remember that setting the data path to `/dev/null` would effectively skip it, but that's a cumbersome way). This would make short benchmarking & debugging much more efficient...

**Comment by lizziel** [comment]
You can add logicals to HEMCO_Config.rc, wrap the emissions you want to skip in a condition for it, and set it to false. This will prevent ExtData from reading them. I believe if you set general emissions to false in input.geos then ExtData will still try to read HEMCO_Config.rc so as to allow use of HEMCO even for non-emissions, e.g. masks.

--
Lizzie Lundgren
Scientific Programmer
GEOS-Chem Support Team
geos-chem-support@as.harvard.edu<mailto:geos-chem-support@as.harvard.edu>
http://wiki.geos-chem.org/GEOS-Chem_Support_Team

Please direct all GEOS-Chem support issues to the entire GEOS-Chem Support Team
at geos-chem-support@as.harvard.edu<mailto:geos-chem-support@as.harvard.edu>. This will allow us to serve you better.

**Comment by JiaweiZhuang** [comment]
> wrap the emissions you want to skip in a condition for it, and set it to false.

Do you mean just manually changing 
```
# ExtNr ExtName                on/off  Species
0       Base                   : on    *
    --> HEMCO_RESTART          :       false
    --> AEIC                   :       true
    --> BIOFUEL                :       true
    --> BOND                   :       true
    --> BRAVO                  :       true
...
```

To 

```
# ExtNr ExtName                on/off  Species
0       Base                   : on    *
    --> HEMCO_RESTART          :       false
    --> AEIC                   :       false
    --> BIOFUEL                :       false
    --> BOND                   :       false
    --> BRAVO                  :       false
...
```

Or there is a more advanced grouping option?

**Comment by lizziel** [comment]
Exactly. I checked a recent log and this does work, but let me know if you see differently. Note that even if ExtData does not read the data HEMCO will still check that the file format is correct, so you can’t put garbage within a block that is off.

--
Lizzie Lundgren
Scientific Programmer
GEOS-Chem Support Team
geos-chem-support@as.harvard.edu<mailto:geos-chem-support@as.harvard.edu>
http://wiki.geos-chem.org/GEOS-Chem_Support_Team

Please direct all GEOS-Chem support issues to the entire GEOS-Chem Support Team
at geos-chem-support@as.harvard.edu<mailto:geos-chem-support@as.harvard.edu>. This will allow us to serve you better.

**Comment by JiaweiZhuang** [comment]
It worked like a charm. Reduced ExtData time by 40% and total time by 20% for a 2-day run. 

- [run_2days_18core_true_noEMIS.log](https://github.com/geoschem/gchp/files/2761744/run_2days_18core_true_noEMIS.log)
