### ISSUE TITLE
[BUG/ISSUE] $ARCH environment variable breaks ESMF compilation

### ISSUE THREAD

**Issue by JiaweiZhuang** [geoschem/gchp_legacy#2]
I suggest changing this code

https://github.com/geoschem/gchp/blob/07f4130cdee6a784698b885339a54ba65ede2717/GIGC.mk#L84-L87

to:   (no conditional)

```
ARCH := $(shell uname -s) 
```

or simply:   (since we won't compile GCHP on non-Linux anyways)

```
ARCH := Linux
```

On some systems (e.g Amazon Linux AMI), `ARCH` is set to `amd64`, then `ESMF/build/common.mk` will be looking for the nonexistent `amd64.gfortran.default` in `ESMF/build_config/`. Forcing `ARCH` to `Linux` ensures that `Linux.gfortran.default` is always used.

The full log with incorrect `ARCH` for record: [compile_error.log](https://github.com/geoschem/gchp/files/2646934/compile_error.log)

**Comment by lizziel** [comment]
I think this is a good idea. I will put the update into 12.1.1. Thanks for suggesting it.
