### ISSUE TITLE
[QUESTION] A question about process geos-chem with by pbs?  

### ISSUE THREAD

**Issue by gc13141112** [geoschem/gchp_legacy#21]
#! /bin/csh -f

#PBS -N testgeoschem
#PBS -q batch
#PBS -l walltime=8:00:00
#PBS -l nodes=2:ppn=40
#PBS -o /public/cmaq/standard/geoschem/UT/runs/4x5_standard
#PBS -e /public/cmaq/standard/geoschem/UT/runs/4x5_standard
#PBS -V
mpiexec.hydra -f machinefile -np 80 ./geos

**Comment by yantosca** [comment]
It is hard for the GCST to assist with this type of problem, as the process by which batch jobs are submitted differs on every computer system.  If you are having problems submitting the job, we recommend talking with your IT staff (or at least the person who maintains the PBS software).
