### ISSUE TITLE
[DISCUSSION] Stretched grid or nested grid for local mesh refinement

### ISSUE THREAD

**Issue by JiaweiZhuang** [geoschem/gchp_legacy#24]
Had a conservation with @LiamBindle and just want to put together my thoughts on whether to choose stretched grid or nested grid. I am still not fully convinced that grid stretching is the right choice. It is indeed the easiest solution from a software engineering perspective. But since the potential primary developer @LiamBindle is good at software engineering, implementing the alternative way (nested grid) might not be a super big challenge. More detailed below.

## Major references

FV3 main website:
- https://www.gfdl.noaa.gov/fv3/
- Especially the grid part: https://www.gfdl.noaa.gov/fv3/fv3-grids/

The original papers on nested and stretched grids:
- A Two-Way Nested Global-Regional Dynamical Core on the Cubed-Sphere Grid (https://journals.ametsoc.org/doi/full/10.1175/MWR-D-11-00201.1)
- High-Resolution Climate Simulations Using GFDL HiRAM with a Stretched Global Grid (https://journals.ametsoc.org/doi/full/10.1175/JCLI-D-15-0389.1)

Cubed-sphere and stretched grid illustration:
- http://acmg.seas.harvard.edu/geos/cubed_sphere.html

## Pros and Cons of the two approaches

Reasons to favor the stretched cubed-sphere:
- Easy to implement. It requires minimal modification to the software architecture (GMAO MAPL). The MPI domain decomposition would work exactly the same as the normal cubed-sphere grid. On the contrary, the nested version requires more fundamental chances to MAPL, to allow two different domains to run at the same time (also some load-balancing issues). 
- It automatically enables a "two-way" feedback between the coarse and the fine grids. The two-way nesting requires more careful tuning to get the dynamics right (reflecting waves, etc.). I don't think offline advection will have those problems, though.

Reasons to favor the nested cubed-sphere:
- Less regridding problems. I don't think we will have the native stretched metfield archive, so we will probably need to regrid the metfield from the normal cubed-sphere grid (or even the current lat-lon) to the stretched cubed-sphere. I am seriously concerned about how the wind field (and mass fluxes in the future) is processed. Recall the early wind regridding & transport problem around the poles, due to lat-lon to cube regridding. The nested grid doesn't have this problem because both the inner and the outer regions are still normal cubed-sphere, and the wind regridding does not change the direction of vector basis. Vector regridding is not a very well studied problem (for recent work see [Pletzer and Hayek, 2019](https://journals.ametsoc.org/doi/full/10.1175/MWR-D-18-0146.1)), and gets even tricker when coupled with advection.
- More flexible time stepping. The stretched grid requires a uniform time step for all regions. The CFL is basically limited by the smallest cell. The time step on the coarser side will be unnecessarily short. This wastes computing resources. On the contrary, a nested domain can use a different time step.
- Easier to handle resolution-dependent parameterizations. With grid nesting you still get a chance to set different parameters for the global and the nested domains. With grid stretching you almost have to use the same scheme everywhere. This might be less a problem with the recent implementation of the (somewhat) grid-independent convection and emission. But still worth pointing out.
- It is a more flexible grid refinement. For example, to study the US-China transport problem, you can place two nested domains over the two countries. With stretching you can only zoom-in to one country; the other side has to be coarse.

## My take-aways

Overall I feel that the stretched grid will involve more verification on the numerical scheme but less software engineering disasters, while the nested grid will involve more software engineering but less numerical troubles. For scientific uses I feel that grid nesting is a bit more flexible.

I recommend talking to the GFDL-FV3 team before starting any real work. They will have a much better idea on how the two methods compare...

It would also be useful to collect opinions from users, to see which one is more in-demand.

**Comment by LiamBindle** [comment]
Hi @JiaweiZhuang,

Thanks again for writing this up. This has been really helpful. 

When you have a change, could you expand on your concerns about regridding the wind fields and mass fluxes to a stretched grid? Are you concerned about regridding all vector fields in the met archives? 

You mention that the cube sphere's vector bases could make regridding especially challenging. But, the normal cube sphere's vector bases are also different from the lat-lon's bases, so why is regridding onto the stretched grids vector bases any more challenging? I thought regridding between grids with different horizontal vector bases was routine. Doesn't ESMF's regridding support this?

Lastly, could you fill me in on the early wind and transport problems? I wasn't involved with GCHP at that point, so I'm not familiar with the issues.

cc: @lizziel, @sdeastham

Thanks,

Liam

**Comment by JiaweiZhuang** [comment]
> But, the normal cube sphere's vector bases are also different from the lat-lon's bases, so why is regridding onto the stretched grids vector bases any more challenging?

Because we shouldn't even regrid the lat-lon wind to cubed-sphere... The online GEOS simulation runs at cubed-sphere grid, but the output data are **postprocessed/regridded to lat-lon grid**   -- this is how we get the GEOS-FP/MERRA2 archive for both GC-classic and GCHP. Our current model simulation is impacted by this double-regridding error which should have been avoided at all.

Ideally, the input wind data should be on the native cubed-sphere grid, and can be ingested by GCHP at the same resolution without regridding. Using lower-res grid or nested grid would just involve a simple averaging of fluxes at cell edges, but not rotating the vector bases. The stretched grid, on the other hand, requires more complex vector regridding (like the current lat-lon -> cubed-sphere) than just averaging fluxes.

**Comment by LiamBindle** [comment]
Ah I see, thanks, that clarifies things. Your concern is that the stretched grid could make what's an existing problem worse.

Why can't we get metfield archives on GEOS-5's native grid?

**Comment by JiaweiZhuang** [comment]
> Your concern is that the stretched grid could make what's an existing problem worse.

Yeah, an exception is that, the online GEOS might also run at stretched grid and archive "native stretched grid" output. But this kind of "fixed stretched grid" seems too limited.

> Why can't we get metfield archives on GEOS-5's native grid?

I guess asking for more archive from GEOS is a complex procedure.... Other people could better answer this.

**Comment by sdeastham** [comment]
It shouldn’t actually be hard; the problem is we need to talk to Bill Putman at GMAO about the process, and he hasn’t been responding to emails for the last few months.

**Comment by LiamBindle** [comment]
I know this is a bit of a long shot, but is there any documentation of this double-regridding error? Or do you know if anyone has any simulation output that I could look at to get a better idea of how bad the problem is?

> It shouldn’t actually be hard; the problem is we need to talk to Bill Putman at GMAO about the process, and he hasn’t been responding to emails for the last few months.

Maybe @lizziel and I should talk to them about getting access to these archives during our visit then. I'll add that to my list of things.

**Comment by sdeastham** [comment]
The archives don’t yet exist. The problem is that we need Bill to sign off on our proposed method to convert between dry and moist tracer mass mixing ratios: https://docs.google.com/document/d/1IQfDbb-kIyZSCTXxhaKyh8s1lP4woWszx_xp9edmCgQ/edit?usp=sharing
The big question is whether we think more information is needed, and what the size of the errors will be from using interpolated surface pressure and specific humidity with time-averaged mass fluxes and courant numbers.

**Comment by JiaweiZhuang** [comment]
> is there any documentation of this double-regridding error?

In early days (~2016) @sdeastham and I saw an excessive downward flux near the poles due to wind regridding. Here's the configuration I remember:
- Read input wind field at 4x5 lat-lon grid
- Run model at C48 resolution or higher
- Only turn on advection (disable other components) to highlight the error

This led to a lot of stratospheric ozone coming down to the surface. Haven't tried to reproduce this in recent versions. Not sure whether this issue is still there.

**Comment by LiamBindle** [comment]
Thanks, I'm going to take a closer look at this. I'll follow up early next week.

**Comment by lizziel** [comment]
This discussion thread has not been touched for a over year, although is still salient. @LiamBindle, would you like to transfer this to [GCHPctm](https://github.com/geoschem/gchpctm) or close it out?

**Comment by LiamBindle** [comment]
@lizziel this can be closed
