### ISSUE TITLE
[DISCUSSION] Multi-node MPI runs with Singularity or Charliecloud containers

### ISSUE THREAD

**Issue by JiaweiZhuang** [geoschem/gchp_legacy#25]
Killian Murphy from University of York (@kilicomu) is interested in testing multi-node container runs. If that works it will greatly simplify GCHP installation on HPC cluster environment -- a wonderful achievement!

Here I am putting together all the information I know.

## Major references

Official docs:
- Singularity documentation: https://www.sylabs.io/docs/
- Singularity GitHub repo: https://github.com/sylabs/singularity
- Charliecloud documentation: https://hpc.github.io/charliecloud/
- Charliecloud GitHub repo: https://github.com/hpc/charliecloud 

Papers: 
- Singularity: Scientific containers for mobility of compute (https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0177459)
- Charliecloud: unprivileged containers for user-defined software stacks in HPC (https://dl.acm.org/citation.cfm?id=3126925)
- A Tale of Two Systems: Using Containers to Deploy HPC Applications on Supercomputers and Clouds (https://www.osti.gov/biblio/1483132). This paper (from Sandia Lab) tested Singularity on Cray, using HPCG with up to 768 cores. 
- Is Singularity-based Container Technology Ready for Running MPI Applications on HPC Clouds? (https://dl.acm.org/citation.cfm?id=3147231) This paper (from OSU) tested Singularity on Intel Haswell and KNL clusters, using MPI collectives with up to 128 cores.

Deployment at institutions
- Singularity on Harvard Odyssey: https://www.rc.fas.harvard.edu/resources/documentation/software/singularity-on-odyssey/
- Singularity on Stanford Sherlock: https://www.sherlock.stanford.edu/docs/software/using/singularity/
- Charliecloud on NASA Pleiades: https://www.nas.nasa.gov/hecc/support/kb/running-a-charliecloud-container-image-on-pleiades_561.html

## Status of multi-node MPI runs

None of the above deployments have documented how to run multi-node MPI jobs. The Pleiades doc even warns that

> WARNING: Running MPI applications across multiple Pleiades nodes with containers is not currently recommended, as the tests performed by NAS staff are not always successful. If you want to experiment with it, be aware that you need to have some MPI implementations available outside of the containers.

One major issue is MPI compatiblity, as noted by [Singularity 2.5 docs](https://singularity.lbl.gov/docs-hpc):

> Another result of the Singularity architecture is the ability to properly integrate with the Message Passing Interface (MPI). Work has already been done for out of the box compatibility with Open MPI (both in Open MPI v2.1.x as well as part of Singularity). 

> What are supported Open MPI Version(s)? To achieve proper container’ized Open MPI support, you should use Open MPI version 2.1. There are however three caveats:
> 1. Open MPI 1.10.x may work but we expect you will need exactly matching version of PMI and Open MPI on both host and container (the 2.1 series should relax this requirement)
> 2. Open MPI 2.1.0 has a bug affecting compilation of libraries for some interfaces (particularly Mellanox interfaces using libmxm are known to fail). If your in this situation you should use the master branch of Open MPI rather than the release.
> 3. Using Open MPI 2.1 does not magically allow your container to connect to networking fabric libraries in the host. If your cluster has, for example, an infiniband network you still need to install OFED libraries into the container. Alternatively you could bind mount both Open MPI and networking libraries into the container, but this could run afoul of glib compatibility issues (its generally OK if the container glibc is more recent than the host, but not the other way around)

Singularity 3.0+ even completely removes the docs on multi-node MPI runs.

I've also heard that NVIDIA is doing some multi-node container development: https://info.nvidia.com/emea-gpu-accelerated-multi-node-hpc-workloads-regpage.html
But haven't found more publicly-available information.

## Where to start

Before testing GCHP at all, one should run [OSU](http://mvapich.cse.ohio-state.edu/benchmarks/) or [Intel MPI benchmarks](https://github.com/intel/mpi-benchmarks). We can effectively predict GCHP performance just from MPI latency/bandwidth. I am particularly curious about the latency overhead of containers.

This is definitely at an early stage. Any successful tests and reproducible examples will be valuable.

**Comment by JiaweiZhuang** [comment]
A new announcement today from the Singularity team:
- A New Open Source Project Integrates Singularity and Slurm via Kubernetes https://www.sylabs.io/2019/05/introducing-hpc-affinities-to-the-enterprise-a-new-open-source-project-integrates-singularity-and-slurm-via-kubernetes/

Maybe this can be used with [Amazon EKS](https://aws.amazon.com/eks/).

**Comment by JiaweiZhuang** [comment]
Interestingly, Alibaba cloud already supports RDMA-enabled containers:

- Using RDMA on Container Service for Kubernetes https://www.alibabacloud.com/blog/using-rdma-on-container-service-for-kubernetes_594462

They got a bandwidth of ~5500 MB/s from `ib_read_bw`. The network latency is not shown in the post, but I guess it should be ~1 us, close to an InfiniBand cluster. Not sure what's their container runtime, but probably not Docker.

Welcome anyone to test it out. I probably don't have time to test it on my own...

**Comment by JiaweiZhuang** [comment]
A very well-written paper just released today:

- Evaluation of Docker Containers for Scientific Workloads in the Cloud: https://arxiv.org/abs/1905.08415

They were able to use Docker over InfiniBand RDMA with very low overhead!

**Comment by JiaweiZhuang** [comment]
A new post today: [Benchmarking MPI Applications in Singularity Containers on Traditional HPC and Cloud Infrastructures](https://insidehpc.com/2019/06/benchmarking-mpi-applications-in-singularity-containers-on-traditional-hpc-and-cloud-infrastructures/)
Covers:
- Overview of recent HPC + cloud trend (as of 2019/05)
- OSU bandwidth/latency benchmark on local HPC and Azure
- MPICH vs OpenMPI compatibility issues for Singularity

**Comment by JiaweiZhuang** [comment]
Just notice a new post today on using Singularity + MPI on Azure: [Accelerating HPC Containers on Azure](https://techcommunity.microsoft.com/t5/Azure-Compute/Accelerating-HPC-Containers-on-Azure/ba-p/807323)

**Comment by lizziel** [comment]
@JiaweiZhuang Thanks for sharing. Has anyone attempted running GCHP on Azure? Regardless, I would think the equivalent advances for multi-node capability on other cloud platforms can't be far behind. I'm hopeful.

From the blog:
```
The latest release also includes a new MPI interface for multi-node job execution without having
to deal with potential configuration complications between Batch multi-instance tasks, the
selected MPI runtime, and the VM instance size selected. Batch Shipyard now provides an
easy-to-use schema for executing your MPI jobs with support for popular MPI frameworks such
as Open MPI, MPICH, MVAPICH, and Intel MPI. This new interface works seamlessly between
both Singularity and Docker containers, which when combined with Azure's HB/HC instances
with 100Gbit/s EDR InfiniBand, provides unparalleled performance for your distributed HPC
container applications in the cloud.
```

**Comment by JiaweiZhuang** [comment]
Singularity 3.3 adds a new doc on [Singularity and MPI applications](https://sylabs.io/guides/3.3/user-guide/mpi.html). The situation is similar to 2.x that you need to have a compatible MPI installation on the host:

> The drawbacks are:
> The MPI in the container must be compatible with the version of MPI available on the host.
> The configuration of the MPI implementation in the container must be configured for optimal use of the hardware if performance is critical.

**Comment by JiaweiZhuang** [comment]
@lizziel There are definitely examples with multi-node Docker runs (e.g. [AWS Batch Multi-node Parallel Jobs](https://docs.aws.amazon.com/batch/latest/userguide/multi-node-parallel-jobs.html)). They are just less explored, with limited documentations & benchmark results.

**Comment by lizziel** [comment]
Thanks! That satisfies the level of info I need right now.

Lizzie

--
Lizzie Lundgren
Senior Scientific Programmer
GEOS-Chem Support Team
geos-chem-support@g.harvard.edu<mailto:geos-chem-support@g.harvard.edu>

Please direct all GEOS-Chem support emails to the entire GEOS-Chem Support Team<http://wiki.geos-chem.org/GEOS-Chem_Support_Team>. If you are reporting a bug, please create an issue on GitHub<https://github.com/geoschem/>.

**Comment by lizziel** [comment]
@WilliamDowns and @LiamBindle of GCST are working on multi-node MPI runs with containers. I am closing out this discussion for legacy GCHP. Future discussions about multi-node MPI runs using containers may be created at new GCHP repository [GCHPctm](https://github.com/geoschem/gchpctm).
