### ISSUE TITLE
[BUG/ISSUE] HEMCO_Config.rc and ExtData.rc not consistent with GC-classic

### ISSUE THREAD

**Issue by JiaweiZhuang** [geoschem/gchp_legacy#3]
For example, GCHP 12.1.0 still uses the old, multi-year CEDS emission (geoschem/geos-chem#12) :

https://github.com/geoschem/gchp/blob/07f4130cdee6a784698b885339a54ba65ede2717/Run/HEMCO_Config.rc_templates/HEMCO_Config.rc.fullchem#L485-L488

which is different from [GC-classic's](https://github.com/geoschem/geos-chem-unittest/blob/0f18d1db4e6c733feaeeb6bab13f1612f7730d89/runs/shared_inputs/fullchem/HEMCO_Config.template.UCX#L478-L481).

Not sure how to keep them synchronized as the rundir generation is now moved to this repo

**Comment by lizziel** [comment]
Hi Jiawei, thanks for reporting this. Run directory updates in the GEOS-Chem Unit Test repo that are relevant to GCHP will also be put into the GCHP repo run directory template files by GCST. This may not occur simultaneously during development of a new version, however. We'll make sure this update gets into GCHP before the 12.1.0 release.

**Comment by msulprizio** [comment]
Hi Jiawei, The difference in CEDS entries between GCC and GCHP is known and is described on the wiki at http://wiki.seas.harvard.edu/geos-chem/index.php/CEDS_anthropogenic_emissions#Reduce_file_size_for_CEDS_inventory.

> NOTE: GCHP will continue to use the multi-year CEDS files instead of the yearly files. In ExtData.rc, the token %y4 was used in the file paths for the yearly CEDS files. However, MAPL replaces the token with the current simulation year. This causes issues if the simulation year is beyond the last year of CEDS emissions available (2014). To avoid this issue for now, we will revert to using the multi-year CEDS files in HEMCO/CEDS/v2018-04/ instead of the yearly files in HEMCO/CEDS/v2018-08/.

**Comment by JiaweiZhuang** [comment]
@msulprizio Thanks, I just notice that!

**Comment by lizziel** [comment]
I am going to take a look at this issue again since the same functionality appears to work for the volcanic eruption inventory.

**Comment by JiaweiZhuang** [comment]
As of 12.5.0, GCHP still reads the big files in `CEDS/v2018-04`, not the smaller files in `HEMCO/CEDS/v2018-08`. Any updates @lizziel ?

**Comment by lizziel** [comment]
No updates @JiaweiZhuang. However, now that MAPL is updated to a newer version this issue should be revisited. Swapping out the files may no longer be an issue. 12.6 is already being benchmarked but I will test dev/12.7 with the smaller files once development of that version begins.

**Comment by lizziel** [comment]
The annual CEDS files work fine with the new version of MAPL. The ExtData.rc update to use the annual files, same as used by GEOS-Chem Classic, will go into 12.7.0. See https://github.com/geoschem/geos-chem/commit/99964173137de72a26e5e24a005ee4d08138decb if you want to change your config file for earlier versions. Note that in 12.7.0 the run directory is created from the GEOS-Chem repository rather than GCHP.
