### ISSUE TITLE
[BUG/ISSUE] Resolution-dependent bias in surface ozone in 12.5.0

### ISSUE THREAD

**Issue by lizziel** [geoschem/gchp_legacy#34]
There is a positive bias in surface ozone over the southern ocean in GCHP 12.5.0. It shows in comparisons with both GCC 12.5.0 and GCHP 12.4.0 in the [12.5.0 1-month benchmark](http://wiki.seas.harvard.edu/geos-chem/index.php/Benchmark/GEOS-Chem_12.5.0#GCHP_1-month_benchmark). The issue is resolution-dependent and occurs in FV3. This is an open issue on GEOS github: https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/48.

**Comment by lizziel** [comment]
FV3 is moving to a new repository on GEOS-ESM and GEOS-ESM/GEOSgcm_GridComp#48 will be moved. Information about changes to this issue will be documented here for the GCHP community.

**Comment by lizziel** [comment]
This issue persists in dev versions of 13.0.0 which uses MAPL 2.0.

**Comment by LiamBindle** [comment]
I think it's also visible in N2O

**Comment by lizziel** [comment]
This ozone bias in the southern hemisphere is fixed by switching the regridding method of winds from bilinear interpolation to conservative. This update should be made in ExtData.rc for UC;UV, ULL, UVV, U, and V. The update will go into 12.8.0.

**Comment by lizziel** [comment]
The switch to conservative winds regridding introduced a polar stratospheric NOy source in the Arctic. We are now delaying making the fix default until the source of this is better understood. It will not be included in 12.8.

The 1-month benchmark plots for before and after the fix are located here if you would like to take a look: http://ftp.as.harvard.edu/gcgrid/geos-chem/validation/GCHPctm/13.0.0-alpha.3/

**Comment by lizziel** [comment]
The surface ozone bias fix will be included in 12.8 after all. It appears that the polar stratospheric NOy source in the Arctic was a compute cluster fluke, although we are on the lookout for seeing something like it again. Rerunning a 1-month benchmark run made it go away.

The update to fix the ozone bias requires a minor update to MAPL, also to be included in 12.8.0. A remnant of pre-12.5 MAPL remained post-12.5 in which the run was forced to stop if conservative regridding of vectors (winds in our case) was turned on. This alarm was spurious and conservative regridding of vectors is actually possible. The GCHP repository update for 12.8 therefore comments out that forced stop. See https://github.com/geoschem/gchp/commit/ffb5a097efee06321a2b04f9f95669a439a22f84.

This update can be applied to earlier versions of GCHP to bypass the surface ozone bias. Simply change ExtData.rc regrid method for winds from N to Y in the conservative column, and apply the GCHP commit above.

**Comment by sdeastham** [comment]
@lizziel Do you think it's safe to close this issue then?
