### ISSUE TITLE
[FEATURE REQUEST] Allow createRunDir.sh to run silently (no interactive questions)

### ISSUE THREAD

**Issue by JiaweiZhuang** [geoschem/gchp_legacy#38]
## Problem

[createRunDir.sh](https://github.com/geoschem/gchp/blob/90f24d9aeab58c988da1f88263ce7b471f799367/Run/createRunDir.sh) uses interactive questions. Although this is instructive for first-time users, it makes the installation process hard to automate. Automation is crucial in many scenarios: continuous integration (#36), creating new cloud images and containers, allowing Spack installation and Conda installation (geoschem/geos-chem#47). Spack has a thread on the difficulty of handling interactive questions: spack/spack#7983. In general, removing all interactive parts in the installation process will make any kinds of automatic deployments much easier. 

So far I've been using a hacky [script](https://github.com/geoschem/geos-chem-cloud/blob/26118d097203276373af8c1c7e03d4f774b28a5f/scripts/build_environment/GCHP/deploy_GCHP.sh) to automate the process of building GCHP. To handle the questions from `createRunDir.sh`, I simply pipe the answers to it:

```bash
rm $HOME/.geoschem/config
printf "$HOME/ExtData \n 2 \n 1 \n $HOME/tutorial \n gchp_standard \n n" | ./createRunDir.sh
```

Each item corresponds  to: input data path, simulation type (2 = standard), metfield type (1 = GEOSFP), rundir parent path, rundir name, whether to version-control rundir.

There are multiple problems with this:
- The `printf` body is difficult to understand, as it only shows the answers, not the questions. 
- It is difficult to track the changes in the questions. For example 8a6455645031dde24b76d22ab9dc2a9d1e127274 adds the path to `gFTL`, so the new answer string should be changed to `"$HOME/ExtData \n $HOME/gFTL/install ..."`
- The `config` file only answers part of the questions (file paths, but not simulation types), and the existence of this file will change the total number of questions asked. 

## Suggestions

Ideally,  the script will have strictly two modes: interactive and silent, and nothing in between (no partial answers, to avoid incomplete & stale config files)

The `config` file should describe all the questions including simulation types, etc. Then, the rundir creation is simply:

```
./createRunDir.sh --silent=config
```

The config file may be created manually, or generated by running the script interactively.

As a reference, Intel compilers also have an interactive installation process by default, but also supports [Silent Installation](https://software.intel.com/en-us/articles/intel-compilers-for-linux-version-111-silent-installation-guide).

**Comment by lizziel** [comment]
I think this feature would also help create many run directories at once, if ever anyone wants to do that. I took a first pass at this, off of GCHP 12.6.1. Instructions are in the createRunDir.sh header. Please give it a try and let me know what you think.
https://github.com/geoschem/gchp/commit/380ed9b90f31094bab8f9e8463981e20c8b5284a

**Comment by lizziel** [comment]
We are planning on putting this capability into 13.0.0.

**Comment by lizziel** [comment]
@LiamBindle worked on something similar that will address this feature request. See GEOS-Chem PR https://github.com/geoschem/geos-chem/pull/459. We anticipate it going into GEOS-Chem 13.1 for use with both GEOS-Chem Classic and GCHP. I am therefore closing this feature request.
