### ISSUE TITLE
[BUG/ISSUE] "ar: memuse.o: No such file or directory" error when building GCHP 12.5.0 with gcc9.2.0

### ISSUE THREAD

**Issue by JiaweiZhuang** [geoschem/gchp_legacy#40]
**Describe the bug**

I got this compile error when building GCHP 12.5.0 with GCC 9.2.0 on Ubuntu (will test other environments later):

```
ar cr libGFDL_fms_r4.a amip_interp.o astronomy.o axis_utils.o column_diagnostics.o constants.o atmos_ocean_fluxes.o coupler_types.o ensemble_manager.o data_override.o diag_axis.o diag_data.o diag_grid.o diag_manager.o diag_output.o diag_util.o cloud_interpolator.o drifters_comm.o drifters_core.o drifters.o drifters_input.o drifters_io.o quicksort.o stock_constants.o xgrid.o fft99.o fft.o field_manager.o fm_util.o fms.o fms_io.o test_fms_io.o horiz_interp_bicubic.o horiz_interp_bilinear.o horiz_interp_conserve.o horiz_interp.o horiz_interp_spherical.o horiz_interp_type.o memuse.o memutils.o create_xgrid.o gradient_c2l.o gradient.o grid.o interp.o mosaic.o mosaic_util.o read_mosaic.o mpp_data.o mpp_domains.o mpp.o mpp_io.o mpp_memutils.o mpp_parameter.o mpp_pset.o mpp_utilities.o mpp_efp.o nsclock.o test_mpp_domains.o test_mpp.o test_mpp_io.o test_mpp_pset.o threadloc.o oda_core.o oda_types.o write_ocean_data.o xbt_drop_rate_adjust.o platform.o MersenneTwister.o random_numbers.o sat_vapor_pres.o sat_vapor_pres_k.o station_data.o time_interp_external.o time_interp.o get_cal_time.o time_manager.o gaussian_topog.o topography.o tracer_manager.o tridiagonal.o test_xgrid.o diag_table.o diag_manifest.o 
ar: memuse.o: No such file or directory
../GNUmakefile_r4r8:148: recipe for target 'libGFDL_fms_r4.a' failed
gmake[9]: *** [libGFDL_fms_r4.a] Error 1
gmake[9]: Leaving directory '/home/ubuntu/gchp_12.5.0/Code.GCHP/GCHP/Shared/GFDL_fms/r4'
gmake[9]: Entering directory '/home/ubuntu/gchp_12.5.0/Code.GCHP/GCHP/Shared/GFDL_fms/r8'
```

Full log: [compile_ubuntu_gcc_openmpi_fail.log](https://github.com/geoschem/gchp/files/3596975/compile_gcc_openmpi_fix_hdf5_still_fail.log)

`memuse.o` (and its source `memuse.c`) is inside `GCHP/Shared/MAPL_Base`; but the above compile command is executed inside `GCHP/Shared/GFDL_fms/r4`, which contains all `*.o` files needed by the `ar` command **except** the `memuse.o` file.

**To Reproduce**

(I can build a Docker container to show the error if that helps.)

1. Install libraries via:
```
spack -v install gcc@9.2.0
spack compiler add $(spack location -i gcc@9.2.0)
spack -v install netcdf-fortran %gcc@9.2.0 ^netcdf~mpi ^hdf5~mpi+fortran+hl
spack install openmpi+pmi schedulers=slurm %gcc@9.2.0 
```

2. Apply the HDF5 fix from #37 :`ln -s $(spack location -i hdf5)/lib/* $(spack location -i netcdf)/lib/`

3. Build GCHP 12.5.0 code. The environment is:

```bash
export PATH=$(spack location -i gcc)/bin:$PATH
export PATH=$(spack location -i openmpi)/bin:$PATH
export gFTL=$HOME/gFTL/install/

export CC=gcc
export OMPI_CC=$CC
export CXX=g++
export OMPI_CXX=$CXX
export FC=gfortran
export F77=$FC
export F90=$FC
export OMPI_FC=$FC
export COMPILER=$FC
export ESMF_COMPILER=gfortran
export ESMF_COMM=openmpi
export MPI_ROOT=$(spack location -i openmpi)

export NETCDF_HOME=$(spack location -i netcdf)
export NETCDF_FORTRAN_HOME=$(spack location -i netcdf-fortran)

export GC_BIN="$NETCDF_HOME/bin"
export GC_INCLUDE="$NETCDF_HOME/include"
export GC_LIB="$NETCDF_HOME/lib"

export GC_F_BIN="$NETCDF_FORTRAN_HOME/bin"
export GC_F_INCLUDE="$NETCDF_FORTRAN_HOME/include"
export GC_F_LIB="$NETCDF_FORTRAN_HOME/lib"

export PATH=${NETCDF_HOME}/bin:$PATH
export PATH=${NETCDF_FORTRAN_HOME}/bin:$PATH

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${NETCDF_HOME}/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${NETCDF_FORTRAN_HOME}/lib

export ESMF_BOPT=O
```

**Required information**
- GEOS-Chem/GCHP version: 12.5.0
- Compiler version: gcc 9.2.0
- MPI library and version: OpenMPI 3.1.4 (the problem should independent of MPI )
- netCDF and netCDF-Fortran library version: 4.7.0 and 4.4.5
- Computational environment: AWS cloud, Ubuntu 16.04
- Code modifications: No

**Comment by JiaweiZhuang** [comment]
CentOS + GCC 8.3.0 doesn't seem to have this error (but have other errors; still diagnosing)

**Comment by lizziel** [comment]
Do you get this error with GCC 8.2.0?

**Comment by JiaweiZhuang** [comment]
> Do you get this error with GCC 8.2.0?

GCC 8.x seems to work fine. Maybe this problem is specific to GCC 9.x. This a perfect example where a build matrix (#36) would be extremely useful

**Comment by JiaweiZhuang** [comment]
I am making some containers for GCHP at https://github.com/JiaweiZhuang/docker_gchp. Could be a useful reference for automatic build (cc @LiamBindle)

**Comment by lizziel** [comment]
I am using GCC 8.2.0 + CentOS without issue but haven't tried any newer versions. A build matrix would be perfect.

**Comment by lizziel** [comment]
We are retiring the GNU makefiles in 13.0.0 so I am closing this issue. The there is an issue building 13.0.0 with GCC 9.x then a new issue should be created.
