### ISSUE TITLE
[BUG/ISSUE] MODIS LAI not properly updated at correct time

### ISSUE THREAD

**Issue by lizziel** [geoschem/gchp_legacy#55]
When comparing results from a 2-day run versus 2 consecutive 1-day runs for dry deposition only on (emission, chemistry, wet deposition, mixing, convection, and advection off) there are differences when there should be none. The pattern of differences indicates a possible problem with leaf area index (LAI). 

<img width="1030" alt="drydep_sfc_before" src="https://user-images.githubusercontent.com/651947/68800341-df6a5380-0627-11ea-8185-bf3cd40e8f25.png">

MODIS LAI should be time-interpolated with daily frequency so a 2-day run would include an LAI update. Fixing the values to be constant across the 2-day runs removes the differences, as shown below. However, this is a not an acceptable fix since LAI should be updated daily.

<img width="1022" alt="drydep_sfc_after" src="https://user-images.githubusercontent.com/651947/68800347-e2fdda80-0627-11ea-9182-12aabd5c85fe.png">

**Comment by lizziel** [comment]
This bug if fixed in 12.6.2 commit https://github.com/geoschem/gchp/commit/98202f1247ee772e1d6dde9b4417e508c95e0bab.

**Comment by lizziel** [comment]
It appears that the problem is at the interface between the GEOS-Chem state and the LAI import, specifically with usage of Its_a_new_day function in the GeosUtil/time_mod submodule.

**Comment by lizziel** [comment]
The multi versus single run difference issue for dry deposition only is due to usage of the function ITS_A_NEW_DAY when updating State_Met LAI fields. ITS_A_NEW_DAY does not actually return true if it is a new day but instead uses logic tailored to GEOS-Chem Classic chemistry timesteps and file read. The improper usage of ITS_A_NEW_DAY results in updating LAI in GCHP daily at 00:20:00 rather than 00:00:00 (except at run start). This bug impacts all GCHP runs that span more than one day. A similar issue exists for updating albedo monthly using ITS_A_NEW_MONTH but only impacts runs that span the new month boundary.

**Comment by yantosca** [comment]
Yeah, we can shunt that behavior in ITS_A_NEW_DAY for GCHP.

**Comment by lizziel** [comment]
My fix no longer uses time_mod functions so this shouldn't be necessary. The state_met fields will be updated every timestep like for the other met that are copied from imports.

**Comment by lizziel** [comment]
This issue is fixed in 12.6.2 commit https://github.com/geoschem/gchp/commit/37433a00b88c044a0d7106284a8500b7a9e9c35b.
