### ISSUE TITLE
[BUG/ISSUE]make build_all, gchp error in ESMF: cpp/node/detail/node_iterator.h(64): error: namespace "std" has no member "addressof"

### ISSUE THREAD

**Issue by XunZhangNJU** [geoschem/gchp_legacy#67]
When I compiled GCHP (branch: master), this error occured.
GCHP/ESMF/src/prologue/yaml-cpp/src/ostream_wrapper.cpp -o /GFPS8p/liulei/Code.gchp/GCHP/ESMF/obj/objO/Linux.intel.64.openmpi.default/ostream_wrapper.o
/GFPS8p/liulei/Code.gchp/GCHP/ESMF/src/prologue/yaml-cpp/src/../include/yaml-cpp/node/detail/node_iterator.h(64): error: namespace "std" has no member "addressof"
      node_iterator_value<V>* operator->() { return std::addressof(m_ref); }
                                                         ^

compilation aborted for /GFPS8p/liulei/Code.gchp/GCHP/ESMF/src/prologue/yaml-cpp/src/nodeevents.cpp (code 2)

`../setEnvironment /GFPS8p/liulei/envs/gchp.mpiifort18_openmpi_xun.env `
##########
##########
This my gchp.env:

#------------------------------------------------------------------------------
#                  GEOS-Chem Global Chemical Transport Model                  !
#------------------------------------------------------------------------------
#BOP
#
# !MODULE: gchp.ifort17_openmpi_odyssey.env
#
# !DESCRIPTION: Source this bash file to compile and run GCHP with the
#  Intel Fortran Compiler v17 and MPI implementation OpenMPI on the 
#  Harvard University Odyssey cluster.
#\\
#\\
# !CALLING SEQUENCE:
#  source gchp.ifort17_openmpi_odyssey.env
#
# !REMARKS
#
# !REVISION HISTORY:
#  26 Oct 2016 - S. Eastham  - Initial version
#  03 Feb 2017 - S. Eastham  - Updated for GCHP v1
#  05 Jan 2018 - E. Lundgren - Initial commit
#  See git commit history for subsequent revisions
#EOP
#------------------------------------------------------------------------------
#BOC

if [[ $- = *i* ]] ; then
  echo "Loading modules for GCHP on Odyssey, please wait ..."
fi

#==============================================================================
# %%%%% Clear existing environment variables %%%%%
#==============================================================================
unset GC_BIN
unset GC_INCLUDE
unset GC_LIB
unset GC_F_BIN
unset GC_F_INCLUDE
unset GC_F_LIB
unset ESMF_DIR

#==============================================================================
# Modules (specific to compute cluster)
#==============================================================================

module purge
# module load git/2.17.0-fasrc01

# Modules for CentOS7
module load x86/Intel_Development_Tool/2018
module load x86/openmpi/3.1.0-icc
module load x86/netcdf/4.6.1-with-netcdf

#==============================================================================
# Environment variables
#==============================================================================

# Make all files world-readable by default
umask 022

# Specify compilers
export CC=mpiicc
export OMPI_CC=$CC

export CXX=mpiicpc
export OMPI_CXX=$CXX

export FC=mpiifort
export F77=$FC
export F90=$FC
export OMPI_FC=$FC
export COMPILER=$FC
export ESMF_COMPILER=intel

# MPI Communication
export ESMF_COMM=openmpi
export MPI_HOME=/usr/sw-cluster/apps/parallel_studio_xe_2018_update3_cluster_edition/compilers_and_libraries_2018.3.222/linux/mpi
export MPI_ROOT=$MPI_HOME

# Base paths
export GC_BIN="$NETCDF_HOME/bin"
export GC_INCLUDE="$NETCDF_HOME/include"
export GC_LIB="$NETCDF_HOME/lib"

# Add to primary path
export NETCDF_HOME=/usr/sw-cluster/apps/netcdf-with-netcdf-4
export PATH=${NETCDF_HOME}/bin:$PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${NETCDF_HOME}/lib

# If using NetCDF after the C/Fortran split (4.3+), then you will need to
# specify the following additional environment variables
#export GC_F_BIN="$NETCDF_FORTRAN_HOME/bin"
#export GC_F_INCLUDE="$NETCDF_FORTRAN_HOME/include"
#export GC_F_LIB="$NETCDF_FORTRAN_HOME/lib"
#export PATH=${NETCDF_FORTRAN_HOME}/bin:$PATH
#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${NETCDF_FORTRAN_HOME}/lib

# Set ESMF optimization (g=debugging, O=optimized (capital o))
export ESMF_BOPT=O

# Set path to GMAO Fortran template library (gFTL) install directory
export gFTL=$(readlink -f ./gFTL)

# Specify number number of job slots for build
export NUM_JOB_SLOTS=8

#==============================================================================
# Set memory limits
#==============================================================================

ulimit -c 0                      # coredumpsize
ulimit -l unlimited              # memorylocked
ulimit -u 50000                  # maxproc
ulimit -v unlimited              # vmemoryuse
ulimit -s unlimited              # stacksize

#==============================================================================
# Print information for clarity
#==============================================================================

module list
echo ""
echo "Environment variables set:"
echo ""
echo "LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}"
echo ""
echo "ESMF_COMM: ${ESMF_COMM}"
echo "ESMP_BOPT: ${ESMF_BOPT}"
echo "MPI_ROOT: ${MPI_ROOT}"
echo ""
echo "CC: ${CC}"
echo "OMPI_CC: ${OMPI_CC}"
echo ""
echo "CXX: ${CXX}"
echo "OMPI_CXX: ${OMPI_CXX}"
echo ""
echo "FC: ${FC}"
echo "F77: ${F77}"
echo "F90: ${F90}"
echo "OMPI_FC: ${OMPI_FC}"
echo "COMPILER: ${COMPILER}"
echo "ESMF_COMPILER: ${ESMF_COMPILER}"
echo ""
echo "GC_BIN: ${GC_BIN}"
echo "GC_INCLUDE: ${GC_INCLUDE}"
echo "GC_LIB: ${GC_LIB}"
echo ""
#echo "GC_F_BIN: ${GC_F_BIN}"
#echo "GC_F_INCLUDE: ${GC_F_INCLUDE}"
#echo "GC_F_LIB: ${GC_F_LIB}"
#echo ""
echo "Done sourcing ${BASH_SOURCE[0]}"

###########################################
So how to fix this error？ and why?

**Comment by lizziel** [comment]
It is hard to say based on the information provided. If you add the extension .txt to your text files you can then drag and drop them into a new issue. Please do this for your environment file and compile log.

**Comment by lizziel** [comment]
I am closing out this issue due to lack of response. Feel free to reopen or create a new issue if you are still having problems with GCHP.
