### ISSUE TITLE
[FEATURE REQUEST] Using pre-built ESMF to reduce compile time and memory

### ISSUE THREAD

**Issue by JiaweiZhuang** [geoschem/gchp_legacy#7]
This issue is just to track the progress of separating ESMF from GCHP source code. This would solve #4.

Note that ESMF is already a conda package: https://anaconda.org/conda-forge/esmf 
(This is how my xESMF gets installed)
But it only contains 7.0.0+, not the ancient 5.2.0 used in GCHP.

**Comment by lizziel** [comment]
I am in the process of updating ESMF in GCHP to the last public release (7.1.0r). This is a requirement for compatibility with a newer version of MAPL that will be part of an upcoming GCHP version. Separating ESMF from GCHP source code will be a later activity.

**Comment by lizziel** [comment]
We need to use a beta version of ESMF 8.0.0 for compatibility with MAPL 1.0.0 (development currently in progress). We will not separate ESMF out as an external module by default until v8 is released and tested with GCHP.

However, I have successfully separated ESMF out of GCHP without issue. If you would like to do this yourself for your particular application I can share with you the steps to take.

**Comment by lizziel** [comment]
Pre-built ESMF will be used in GCHP starting in version 13.0 to be released early next year. Users will need to download and build ESMF themselves. While GCHP build will use CMake, ESMF will still use GNU Make.
